#!/bin/bash
#PBS -l nodes=1:ppn=16
#PBS -l walltime=02:00:00

# Copyright (c) 2020 brainlife.io at University of Texas at Austin and Indiana University
# 
# This is the main file run by the brainlife.io orchestration system
#
# Author: Franco Pestilli

# make output directory
mkdir -p output

git clone https://github.com/DanNBullock/OCT_scripts.git

set -e
set -x

singularity exec docker://brainlife/dipy:1.4.0 ./main.py

# copy the plot.pngs to product.json
cat << EOF > product.json
{
    "brainlife": [
        { 
            "type": "image/png", 
            "name": "radarPlot",
            "base64": "$(base64 -w 0 output/radarPlot.png)"
        },
        { 
            "type": "image/png", 
            "name": "scatterPlot",
            "base64": "$(base64 -w 0 output/scatterPlot.png)"
        }
    ]
}
EOF

echo "all done"
