#!/bin/bash
#PBS -l nodes=1:ppn=1
#PBS -l walltime=00:15:00

#brainlife doesn't clone sub module
#git clone https://github.com/DanNBullock/OCT_scripts.git
git submodule init
git submodule update --remote

set -e
set -x

mkdir -p output

singularity exec docker://brainlife/dipy:1.4.0 ./main.py

# copy the plot.pngs to product.json
cat << EOF > product.json
{
    "brainlife": [
        { 
            "type": "image/png", 
            "name": "radarPlot",
            "base64": "$(base64 -w 0 output/radarPlot.png)"
        },
        { 
            "type": "image/png", 
            "name": "scatterPlot",
            "base64": "$(base64 -w 0 output/scatterPlot.png)"
        }
    ]
}
EOF

echo "all done"
